version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: hello-world

phases:
  pre_build:
    commands:
      - cd trivia-backend/
      - export IMAGE_TAG=$CODEBUILD_BUILD_ID
      - export ECR_REPO=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - $(aws ecr get-login --no-include-email)
  build:
    commands:
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG
      - docker push $ECR_REPO:$IMAGE_TAG
