version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: hello-world
    ECR_REPO: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
    IMAGE_TAG: $CODEBUILD_BUILD_ID

phases:
  build:
    commands:
      - cd trivia-backend/
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG
      - $(aws ecr get-login --no-include-email)
      - docker push $ECR_REPO:$IMAGE_TAG
