version: 0.2

phases:
  install:
    commands:
      - npm install -g aws-cdk
      - npm ci
  build:
    commands:
      - npm run build
      - mkdir build
      - cdk synth -o build/ --app "node bin/shared-infrastructure.js"

artifacts:
  files:
    - build/*
  discard-paths: yes