version: 0.2

phases:
  install:
    commands:
      - cd infrastructure/
      - npm install -g aws-cdk
      - npm ci
  build:
    commands:
      - npm run build
      - npm run synth-infra

artifacts:
  files:
    - build/*
  discard-paths: yes